name: Release

on:
  push:
    tags:
      - 'v*'
      - '!v*-testing'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Environment
        uses: ./.github/actions/prepare-environment
        with:
          project: XIVRusUpdater

      - name: Build and Upload Artifact
        uses: ./.github/actions/build-with-artifact
        with:
          project: XIVRusUpdater
          version: ${{ github.ref_name }}

      - name: Create Release
        uses: ./.github/actions/create-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project: XIVRusUpdater
          version: ${{ github.ref_name }}
          prerelease: false

      - name: Update repo.json
        uses: ./.github/actions/update-repo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project: XIVRusUpdater
          version: ${{ github.ref_name }}
          testing: false